### ISSUE TITLE
Words swapped if <br> in text

### ISSUE THREAD

**Issue by lbried** [pauljz/autoabbr#4]
This is my input : <div id="MyDiv"><br>the<br>US<br>of<br>america<br></div>

If I do this : 
$("#MyDiv").autoAbbr({ addClass:'autoAbbr', includeWord : false, src: '/local/autoabbr.json') });

this is the result : 

<div id="MyDiv"><br>the<br><br>of<br>america<br><abbr class="autoAbbr" data-definition="us" title="United States">US</abbr></div>

:-(

**Comment by robocoder** [comment]
Isn't this fixed by #5?

**Comment by pauljz** [comment]
Yes, this appears to have been fixed by #5!
